// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK1k3Moc_Y8Rgl-kjUTFKtycv1rOvKM1c',
    appId: '1:68638664524:web:54c226e302e3bd62c851e9',
    messagingSenderId: '68638664524',
    projectId: 'fire-auth-9044e',
    authDomain: 'fire-auth-9044e.firebaseapp.com',
    storageBucket: 'fire-auth-9044e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9zDXJqHeiQlI2UwGuOD7GHOc31DlNbeE',
    appId: '1:68638664524:android:07460189f55cf5a4c851e9',
    messagingSenderId: '68638664524',
    projectId: 'fire-auth-9044e',
    storageBucket: 'fire-auth-9044e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC9HsnIBxgp8XMkzHo9HXAQ69pp1mT3q0',
    appId: '1:68638664524:ios:d5da7f468849bcbcc851e9',
    messagingSenderId: '68638664524',
    projectId: 'fire-auth-9044e',
    storageBucket: 'fire-auth-9044e.firebasestorage.app',
    iosBundleId: 'com.example.assessmentMobileAppProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC9HsnIBxgp8XMkzHo9HXAQ69pp1mT3q0',
    appId: '1:68638664524:ios:d5da7f468849bcbcc851e9',
    messagingSenderId: '68638664524',
    projectId: 'fire-auth-9044e',
    storageBucket: 'fire-auth-9044e.firebasestorage.app',
    iosBundleId: 'com.example.assessmentMobileAppProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBK1k3Moc_Y8Rgl-kjUTFKtycv1rOvKM1c',
    appId: '1:68638664524:web:6b640d3490908470c851e9',
    messagingSenderId: '68638664524',
    projectId: 'fire-auth-9044e',
    authDomain: 'fire-auth-9044e.firebaseapp.com',
    storageBucket: 'fire-auth-9044e.firebasestorage.app',
  );
}
