// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvWdjl_GfouQC0-8pbOPw9k82QLFilXbE',
    appId: '1:792346799514:web:5c1a7bdb41acb050911e23',
    messagingSenderId: '792346799514',
    projectId: 'project-nodered-53287',
    authDomain: 'project-nodered-53287.firebaseapp.com',
    databaseURL: 'https://project-nodered-53287-default-rtdb.firebaseio.com',
    storageBucket: 'project-nodered-53287.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHMvSSJ3ewEbJX_1Zt4QeWgnNeThaoUgM',
    appId: '1:792346799514:android:796e957a22f3d04d911e23',
    messagingSenderId: '792346799514',
    projectId: 'project-nodered-53287',
    databaseURL: 'https://project-nodered-53287-default-rtdb.firebaseio.com',
    storageBucket: 'project-nodered-53287.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHsnSDmSCAlhYn0nHu4CrEo_x0GtSNCh8',
    appId: '1:792346799514:ios:542435052318e109911e23',
    messagingSenderId: '792346799514',
    projectId: 'project-nodered-53287',
    databaseURL: 'https://project-nodered-53287-default-rtdb.firebaseio.com',
    storageBucket: 'project-nodered-53287.firebasestorage.app',
    iosBundleId: 'com.example.assessmentMobileAppProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHsnSDmSCAlhYn0nHu4CrEo_x0GtSNCh8',
    appId: '1:792346799514:ios:542435052318e109911e23',
    messagingSenderId: '792346799514',
    projectId: 'project-nodered-53287',
    databaseURL: 'https://project-nodered-53287-default-rtdb.firebaseio.com',
    storageBucket: 'project-nodered-53287.firebasestorage.app',
    iosBundleId: 'com.example.assessmentMobileAppProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvWdjl_GfouQC0-8pbOPw9k82QLFilXbE',
    appId: '1:792346799514:web:c84b29ea71265787911e23',
    messagingSenderId: '792346799514',
    projectId: 'project-nodered-53287',
    authDomain: 'project-nodered-53287.firebaseapp.com',
    databaseURL: 'https://project-nodered-53287-default-rtdb.firebaseio.com',
    storageBucket: 'project-nodered-53287.firebasestorage.app',
  );

}